#!/usr/bin/env node

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { createInterface } from 'readline';

import process from 'node:process';

const rl = createInterface({
  input: process.stdin,
  output: process.stdout,
});

/**
 * Prompts the user for input
 * @param {string} question - The question to ask
 * @param {string} defaultValue - Optional default value
 * @returns {Promise<string>} The user's input
 */
const askQuestion = (question, defaultValue = '') => {
  return new Promise(resolve => {
    const prompt = defaultValue
      ? `${question} (default: ${defaultValue}): `
      : `${question}: `;
    rl.question(prompt, answer => {
      resolve(answer.trim() || defaultValue);
    });
  });
};

/**
 * Prompts the user for a required input with validation
 * @param {string} question - The question to ask
 * @param {string} defaultValue - Optional default value
 * @returns {Promise<string>} The user's input (guaranteed to be non-empty)
 */
const askRequiredQuestion = async (question, defaultValue = '') => {
  let value = '';
  while (!value) {
    value = await askQuestion(question, defaultValue);
    if (!value) {
      console.log('❌ This field is required. Please provide a value.\n');
    }
  }
  return value;
};

/**
 * Reads existing .env file and returns its contents as an object
 * @returns {Object} Object with key-value pairs from .env
 */
const readExistingEnv = () => {
  const envPath = '.env';
  if (!existsSync(envPath)) {
    return {};
  }

  const content = readFileSync(envPath, 'utf-8');
  const env = {};
  content.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...valueParts] = trimmed.split('=');
      if (key) {
        env[key.trim()] = valueParts.join('=').trim();
      }
    }
  });
  return env;
};

/**
 * Writes environment variables to .env file
 * @param {Object} envVars - Object with environment variables
 */
const writeEnvFile = envVars => {
  const envPath = '.env';
  let content = '# Environment Variables\n';
  content += '# Generated by setup script\n\n';

  // Group variables by category
  const categories = {
    'Contentful (CMS)': [
      'VITE_CONTENTFUL_SPACE_ID',
      'VITE_CONTENTFUL_ACCESS_TOKEN',
    ],
    'Umami Analytics': ['VITE_UMAMI_WEBSITE_ID', 'VITE_UMAMI_SCRIPT_URL'],
    'Beehiiv (Newsletter)': ['BEEHIIV_API_KEY', 'BEEHIIV_PUBLICATION_ID'],
  };

  // Track which variables have been written
  const writtenVars = new Set();

  // Write categorized variables
  for (const [category, vars] of Object.entries(categories)) {
    const hasVars = vars.some(v => envVars[v]);
    if (hasVars) {
      content += `# ${category}\n`;
      vars.forEach(varName => {
        if (envVars[varName]) {
          content += `${varName}=${envVars[varName]}\n`;
          writtenVars.add(varName);
        }
      });
      content += '\n';
    }
  }

  // Write any remaining variables that aren't in categories (preserve custom vars)
  const unwrittenVars = Object.keys(envVars).filter(
    key => !writtenVars.has(key)
  );
  if (unwrittenVars.length > 0) {
    content += '# Other / Custom Variables\n';
    unwrittenVars.forEach(varName => {
      if (envVars[varName]) {
        content += `${varName}=${envVars[varName]}\n`;
      }
    });
    content += '\n';
  }

  writeFileSync(envPath, content, 'utf-8');
  console.log(`\n✅ Environment variables written to ${envPath}`);
};

/**
 * Main setup function
 */
const main = async () => {
  console.log('🚀 Digicard Setup Script\n');
  console.log(
    'This script will help you configure your environment variables.\n'
  );
  console.log('All variables are required.\n');

  const existingEnv = readExistingEnv();
  const envVars = { ...existingEnv };

  // Define required variables
  const requiredVars = [
    'VITE_CONTENTFUL_SPACE_ID',
    'VITE_CONTENTFUL_ACCESS_TOKEN',
    'VITE_UMAMI_WEBSITE_ID',
    'VITE_UMAMI_SCRIPT_URL',
    'BEEHIIV_API_KEY',
    'BEEHIIV_PUBLICATION_ID',
  ];

  // Contentful variables
  console.log('\n📦 Contentful Configuration');
  console.log('Get these from: Settings → API Keys in your Contentful space\n');
  envVars.VITE_CONTENTFUL_SPACE_ID = await askRequiredQuestion(
    'VITE_CONTENTFUL_SPACE_ID',
    existingEnv.VITE_CONTENTFUL_SPACE_ID || ''
  );

  envVars.VITE_CONTENTFUL_ACCESS_TOKEN = await askRequiredQuestion(
    'VITE_CONTENTFUL_ACCESS_TOKEN',
    existingEnv.VITE_CONTENTFUL_ACCESS_TOKEN || ''
  );

  // Umami Analytics variables
  console.log('\n📊 Umami Analytics Configuration');
  envVars.VITE_UMAMI_WEBSITE_ID = await askRequiredQuestion(
    'VITE_UMAMI_WEBSITE_ID',
    existingEnv.VITE_UMAMI_WEBSITE_ID || ''
  );

  envVars.VITE_UMAMI_SCRIPT_URL = await askRequiredQuestion(
    'VITE_UMAMI_SCRIPT_URL',
    existingEnv.VITE_UMAMI_SCRIPT_URL || ''
  );

  // Beehiiv variables
  console.log('\n📧 Beehiiv Configuration');
  envVars.BEEHIIV_API_KEY = await askRequiredQuestion(
    'BEEHIIV_API_KEY',
    existingEnv.BEEHIIV_API_KEY || ''
  );

  envVars.BEEHIIV_PUBLICATION_ID = await askRequiredQuestion(
    'BEEHIIV_PUBLICATION_ID',
    existingEnv.BEEHIIV_PUBLICATION_ID || ''
  );

  // Validate all required variables are present
  const missingVars = requiredVars.filter(varName => !envVars[varName]);
  if (missingVars.length > 0) {
    console.error('\n❌ Error: Missing required environment variables:');
    missingVars.forEach(varName => {
      console.error(`  - ${varName}`);
    });
    rl.close();
    process.exit(1);
  }

  writeEnvFile(envVars);

  console.log('\n✨ Setup complete!');
  console.log('You can now start the development server with: npm run dev\n');

  rl.close();
};

main().catch(error => {
  console.error('❌ Error:', error.message);
  rl.close();
  process.exit(1);
});
